// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// AltCalc testing module connect
class JumpCaller {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  JumpCaller(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  JumpCaller.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void add(
    double alt,
  ) {
    return _add(
      alt,
    );
  }

  late final _addPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Float)>>('jump_add');
  late final _add = _addPtr.asFunction<void Function(double)>();

  JumpInf info() {
    return _info();
  }

  late final _infoPtr =
      _lookup<ffi.NativeFunction<JumpInf Function()>>('jump_info');
  late final _info = _infoPtr.asFunction<JumpInf Function()>();

  void clear() {
    return _clear();
  }

  late final _clearPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('jump_clear');
  late final _clear = _clearPtr.asFunction<void Function()>();
}

final class UnnamedStruct1 extends ffi.Struct {
  @ffi.Float()
  external double alt;

  @ffi.Float()
  external double speed;
}

final class UnnamedStruct2 extends ffi.Struct {
  @ffi.Float()
  external double alt;

  @ffi.Float()
  external double speed;
}

final class UnnamedStruct3 extends ffi.Struct {
  @ffi.Float()
  external double alt;

  @ffi.Float()
  external double speed;
}

final class UnnamedStruct4 extends ffi.Struct {
  @ffi.UnsignedChar()
  external int mode;

  @ffi.UnsignedLong()
  external int cnt;

  @ffi.UnsignedLong()
  external int tm;

  @ffi.UnsignedLong()
  external int newcnt;

  @ffi.UnsignedLong()
  external int newtm;
}

final class UnnamedStruct5 extends ffi.Struct {
  @ffi.Double()
  external double val;

  @ffi.UnsignedChar()
  external int isbig;

  @ffi.UnsignedLong()
  external int cnt;

  @ffi.UnsignedLong()
  external int tm;
}

final class JumpInf extends ffi.Struct {
  @ffi.UnsignedLong()
  external int interval;

  @ffi.Float()
  external double alt;

  @ffi.Double()
  external double sqdiff;

  external UnnamedStruct1 avg;

  external UnnamedStruct2 app;

  external UnnamedStruct3 sav;

  external UnnamedStruct4 jmp;

  external UnnamedStruct5 sq;
}
